### ISSUE TITLE
https://trtl.bluerockpools.net

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin-pools-json#46]
I was incorrect in my previous PR about https://trtl.bluerockpools.net:8111/stats - it's almost got the same API as a forknote pool, but not quite. E.g. a standard forknote pool has `pool.lastBlockFound`, whilst this API has
```
"lastblock":{"difficulty":318922939,"height":711516,"timestamp":1534322822,"reward":2917738,"hash":"b3f57926efabd7a45e9b32dff5dbaf004b67c963792d2d157c19471763529560"}
```

Perhaps needs a separate type, but is it a bit of a shame with it being so similar.

**Comment by derp-derp-derp** [comment]
Good catch. Maybe that specific pool forked forknote and then made some of their own changes? Or if there are others using it as well then perhaps, like you said, we should add a new type -- e.g. "alt. forknote"

And should we roll back that last PR for now?

**Comment by ZedPea** [comment]
It works fine for turtleminers.club, and I doubt anyone was successfully using this pool anyway due to the incorrect api listing, so I'd keep the previous PR> Probably need to add a new type, I'm not sure if it's custom or just a less known pool.

**Comment by derp-derp-derp** [comment]
What do you think about `forknote-alt` for now?

**Comment by ZedPea** [comment]
Fine with me
