### ISSUE TITLE
add new pool 

### ISSUE THREAD

**Issue by netmonk** [turtlecoin/turtlecoin-pools-json#5]
can you please add https://turtle.coolmining.club ?

**Comment by hensleyrob** [comment]
@netmonk, what's the URL for your api and I'll get you added.

**Comment by netmonk** [comment]
well this is the url of my api :)

**Comment by derp-derp-derp** [comment]
Nice - I didn't realize that the API URL could be only the root domain, but it does appear to work e.g. https://turtle.coolmining.club/live_stats

**Comment by netmonk** [comment]
well i know nginx and reverse proxy :)

**Comment by derp-derp-derp** [comment]
Added :)
