### ISSUE TITLE
TurtleMiners.club

### ISSUE THREAD

**Issue by andrewnk** [turtlecoin/turtlecoin-pools-json#55]
@sudeepb02 It appears that TurtleMiners.club just redirects to http://turtlepool.space/. Since there are already three records for turtlepool.space, can we remove TurtleMiners.club from the json file?

**Comment by sudeepb02** [comment]
Yeah sure. The pool was shut down last month. As some miners were still mining even after all the notifications, they were redirected to turtlepool so as not to waste their hashrate.
