### ISSUE TITLE
Dead / API down pools

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-pools-json#69]
http://grubtoken.justminers.com/ seems offline, as does the API.

http://trtl.cryptoasiapool.com/ is online, but the API does not load: http://trtl.cryptoasiapool.com:8117/stats

I don't know who owns either to contact them. Cryptoasiapool has not been responding to API requests for at least 52 days - I don't have any data on grubtoken, however.

**Comment by derp-derp-derp** [comment]
They seem like shoe-ins for removal. Any objections?

**Comment by derp-derp-derp** [comment]
Last call for objections. :-)

**Comment by DiscoTim** [comment]
seems to use port 8118, http://trtl.cryptoasiapool.com:8118/stats

**Comment by DiscoTim** [comment]
crazybird seems to use https://mining.crazybird.fr:8118/ instead of http://mining.crazybird.fr:8117/
